server:
  port: 10091
  servlet:
    context-path: /video

spring:
  application:
    name: videoService
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: nacos:8848
      config:
        namespace: dev
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace}
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
#    loadbalancer:
#      nacos:
#        enabled: true
  config:
    import:
      - nacos:common-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:video-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true