server:
  port: 11111
spring:
  application:
    name: mcpService
  cloud:
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
    #    loadbalancer:
    #      nacos:
    #        enabled: true
    nacos:
      server-addr: nacos:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
      config:
        namespace: dev
  config:
    import: nacos:mcp-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true