server:
  port: 10086
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 120000000
    nacos:
      username: nacos
      password: nacos
      server-addr: 106.13.105.230:8848
      config:
        namespace: dev
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace}
  config:
    import:
      - nacos:gateway-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:common-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true

logging:
  level:
    reactor:
      netty: DEBUG
    io:
      netty: DEBUG