server:
  port: 10086
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 120000000
    nacos:
      username: nacos
      password: nacos
      server-addr: 106.13.105.230:8848
  config:
    import: nacos:gateway-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true

jwt:
  sign-key: yxyyxhyh
  expire: 66666666

logging:
  level:
    reactor:
      netty: DEBUG
    io:
      netty: DEBUG