server:
  port: 10094

spring:
  application:
    name: aiService
  profiles:
    active: dev
  webflux:
    base-path: /ai/api
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: nacos:8848
      config:
        namespace: dev
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace}
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
    #    loadbalancer:
    #      nacos:
    #        enabled: true
  config:
    import:
      - nacos:common-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:ai-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true