server:
  port: 10094
  #  servlet:
  #    context-path: /ai
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: yixuan
    key-alias: mydomain
  tomcat:
    threads:
      max: 5
      min-spare: 2
    max-connections: 50

spring:
  #  mvc:
  #    servlet:
  #      path: /api
  application:
    name: aiService
  profiles:
    active: dev
  webflux:
    base-path: /ai/api
  cloud:
    nacos:
      server-addr: 106.13.105.230:8848
      config:
        file-extension: yaml # 配置文件名后缀
        shared-configs: # 共享配置
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
    #    loadbalancer:
    #      nacos:
    #        enabled: true
  config:
    import:
      - nacos:common-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  r2dbc:
    url: r2dbc:mysql://110.41.182.125:3306/new_yh
    username: root
    password: wisdom123456789
    pool:
      enabled: true
      initial-size: 1
      max-size: 5
      validation-query: SELECT 1
      max-idle-time: 30000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  ai:
    openai:
      api-key: b09d15b8-25ef-44e1-99d4-8e367939dd95
      base-url: https://ark.cn-beijing.volces.com/api/v3/
      chat:
        options:
          model: deepseek-r1-250528
          temperature: 0.8
        completions-path: /chat/completions
    mcp:
      client:
        type: ASYNC
        sse:
          connections:
            server1:
              url: http://127.0.0.1:11111/
        toolcallback:
          enabled: true

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true # 开启驼峰命名自动映射

#mybatis-plus:
#  type-aliases-package: com.yixuan.yh.ai.pojo
#  mapper-locations: "classpath*:/com/yixuan/yh/**/mapper/*.xml"
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: assign_id # id 为雪花算法生成
#      update-strategy: not_null

logging:
  level:
#    reactor: debug
#    org.springframework.web.reactive: debug
    org.springframework.r2dbc: debug
    org.springframework.r2dbc.core.DefaultDatabaseClient: trace