spring:
  cloud:
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
    #    loadbalancer:
    #      nacos:
    #        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        flow:
          nacos:
            server-addr: 110.41.182.125:8848
            data-id: rule
            group-id: DEFAULT_GROUP
            rule-type: flow
  datasource:
    url: jdbc:mysql://110.41.182.125/new_yh
    username: root
    password: wisdom123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-while-idle: true
      validation-query: select 1
      time-between-eviction-runs-millis: 20000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 110.41.182.125:8848
#      namespace: ""
#      group: DEFAULT_GROUP
#      application: seataServer
#      username: nacos
#      password: nacos
#  data-source-proxy-mode: AT
#  tx-service-group: yx # 事务组名称
#  service:
#    vgroup-mapping: # 事务组与tc集群的映射关系
#      yx: "default"
jwt:
  expire: 66666666
  sign-key: yxyyxhyh

mt:
  console-url: http://47.121.24.225:19998
  core-url: http://47.121.24.225:19999
  bucket-name: user
  username: mt
  password: mt