spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/yh
    username: yh
    password: Qq2434462503.
    pool:
      enabled: true
      initial-size: 1
      max-size: 5
      validation-query: SELECT 1
      max-idle-time: 30000
  ai:
    openai:
      api-key: ${api-key}
      base-url: https://ark.cn-beijing.volces.com/api/v3/
      # base-url: http://localhost:11434/v1
      chat:
        options:
          model: deepseek-r1-250528
          # model: qwen3:4b
          temperature: 0.8
        completions-path: /chat/completions
      embedding:
        api-key: ${api-key}
        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        # base-url: http://localhost:11434
        options:
          model: text-embedding-v4
          # model: qwen3-embedding:4b
          dimensions: 768
    vectorstore:
      milvus:
        client:
          host: milvus
          port: 19530
        collection-name: yh_rag_collection
        initialize-schema: true
        embedding-dimension: 768
        index-type: IVF_FLAT
        metric-type: L2
    mcp:
      client:
        type: ASYNC
        sse:
          connections:
            server1:
              url: http://127.0.0.1:11111/
              # url: http://mcpService
        toolcallback:
          enabled: true