spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/yh
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    pool:
      enabled: true
      initial-size: 1
      max-size: 5
      validation-query: SELECT 1
      max-idle-time: 30000
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: deepseek-v3.2-exp
          temperature: 0.8
        completions-path: /chat/completions
      embedding:
        options:
          model: text-embedding-v4
          # model: qwen3-embedding:4b
          dimensions: 768
    vectorstore:
      milvus:
        client:
          host: milvus
          port: 19530
        collection-name: yh_rag_collection
        initialize-schema: true
        embedding-dimension: 768
        index-type: IVF_FLAT
        metric-type: L2
    mcp:
      client:
        type: ASYNC
        sse:
          connections:
            server1:
              url: http://127.0.0.1:11111/
              # url: http://mcpService
        toolcallback:
          enabled: true