aws:
  url: http://minio:9000
  secret-key: ${MINIO_SECRET_KEY}
  access-key: ${MINIO_ACCESS_KEY}
  bucket: chat

mybatis-plus:
  type-aliases-package: com.yixuan.yh.chat.pojo
  mapper-locations: "classpath*:/com/yixuan/yh/**/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id # id 为雪花算法生成
      update-strategy: not_null