server:
  tomcat:
    threads:
      max: 5
      min-spare: 2
    max-connections: 50

jwt:
  sign-key: yxyyxhyh
  expire: 66666666

spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:mysql://mysql/yh?allowMultiQueries=true
    username: yh
    password: Qq2434462503.
    driver-class-name: com.mysql.cj.jdbc.Driver
    # type: com.alibaba.druid.pool.DruidDataSource
    druid:
      keep-alive: true
      test-while-idle: true
      min-idle: 1
      validation-query: select 1
      time-between-eviction-runs-millis: 20000
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:10085  # Sentinel控制台地址
        port: 8719  # 与控制台交互的端口（默认为8719）
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
  data:
    redis:
      host: redis
      port: 6379
      password: qq2434462503
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
      
seata:
  registry:
    type: nacos
    nacos:
      server-addr: nacos:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seataServer
      username: nacos
      password: nacos
  data-source-proxy-mode: AT
  tx-service-group: yx # 事务组名称
  service:
    vgroup-mapping: # 事务组与tc集群的映射关系
      yx: "default"

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug