alipay:
  url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId:
  appPrivateKey:
  alipayPublicKey:
  notifyUrl:

mybatis-plus:
  type-aliases-package: com.yixuan.yh.order.pojo
  mapper-locations: "classpath*:/com/yixuan/yh/**/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id # id 为雪花算法生成
      update-strategy: not_null