spring:
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 7000MB
#      enabled: false
  # datasource:
  #   url: jdbc:mysql://mysql/yh_video?allowMultiQueries=true
  #   username: yh
  #   password: Qq2434462503.
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   # type: com.alibaba.druid.pool.DruidDataSource
  #   druid:
  #     keep-alive: true
  #     test-while-idle: true
  #     min-idle: 1
  #     validation-query: select 1
  #     time-between-eviction-runs-millis: 20000

mybatis-plus:
  type-aliases-package: com.yixuan.yh.video.pojo
  mapper-locations: "classpath*:/com/yixuan/yh/**/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id # id 为雪花算法生成
      update-strategy: not_null

mt:
  console-url: http://mt:19998
  core-url: http://mt:19999
  bucket-name: video
  username: mt
  password: mt

minio:
  minio-url: http://minio:9000
  secret-key: minioadmin
  access-key: minioadmin
  bucket: video


aws:
  url: http://minio:9000
  secret-key: minioadmin
  access-key: minioadmin
  bucket: video

xxl:
  job:
    admin:
      addresses: http://xxljob:12001/xxl-job-admin
    executor:
      appname: video
      port: 11112
    access-token: 123456

milvus:
  uri: http://milvus:19530