server:
  port: 10093
  servlet:
    context-path: /live
  tomcat:
    threads:
      max: 5
      min-spare: 2
    max-connections: 50

spring:
  mvc:
    servlet:
      path: /api
  application:
    name: liveService
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 106.13.105.230:8848
    #      discovery:
    #        ip: 10.96.51.199
    #        network-interface: wireless_32768
    openfeign:
      httpclient:
        enabled: true # 开启 Feign 对 httpClient 的支持
#    loadbalancer:
#      nacos:
#        enabled: true
  config:
    import:
      - nacos:common-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:live-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 7000MB
#      enabled: false

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true # 开启驼峰命名自动映射
mybatis-plus:
  type-aliases-package: com.yixuan.yh.live.pojo
  mapper-locations: "classpath*:/com/yixuan/yh/**/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id # id 为雪花算法生成
      update-strategy: not_null

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
mt:
  console-url: http://43.139.55.171:19998
  core-url: http://43.139.55.171:19999
  bucket-name: video
  username: mt
  password: mt